### ISSUE TITLE
0.94.6.8.8.35 release violates PVP

### ISSUE THREAD

**Issue by phadej** [audreyt/regex-pcre-builtin#10]
Changing the requirement of function from `Monad` to `MonadFail` is **breaking change**.

`0.94.6.8.8.35` should been released as `0.95.0.8.8.35` (note 0.95, i.e. major bump).

c.f. https://github.com/ChrisKuklewicz/regex-tdfa/issues/29

I'm black-listing 0.94.6.8.8.35 release on Hackage

**Comment by hvr** [comment]
It's also worth noting that http://hackage.haskell.org/package/regex-pcre-0.95.0.0 performed a major ver bump for the very same reason; as will the imminent next `regex-posix` release

**Comment by phadej** [comment]
@audreyt, thank you for prompt response & upload!
