### ISSUE TITLE
Haskell implementation of PCRE

### ISSUE THREAD

**Issue by janakg** [audreyt/regex-pcre-builtin#14]
We are converting facebook's [duckling](https://github.com/facebook/duckling) library to WASM using [asterius](https://github.com/tweag/asterius). Duckling is extensively using regex-PCRE but since all PCRE libraries are dependent on native C implementation or static libraries. We are unable to convert to WASM.

Do you have any plans to support regex-PCRE compatible APIs with Haskell implementation? or can you help us with some suggestions/directions to achieve the same?

**Comment by audreyt** [comment]
Hi! Thank you for reaching out. Have you explored the possibility of calling out to something like https://github.com/stephen-riley/pcre2-wasm through JSFFI?

**Comment by janakg** [comment]
Hi, Thanks for your reply. We have received a similar idea from an author of asterius. But he has mentioned that the C String copy issue might need to be resolved. Please see this for more info.
https://github.com/tweag/asterius/issues/630

**Comment by audreyt** [comment]
OK! As this library is in maintenance-only mode and my day job as Taiwan's digital minister only permits for limited time for development, I'll close this issue here for now.

**Comment by janakg** [comment]
@audreyt  I understand. Thanks for responding to our issue.
