### ISSUE TITLE
Make a revision on hackage to support GHC 9.0.1

### ISSUE THREAD

**Issue by andreasabel** [audreyt/regex-pcre-builtin#18]
`regex-pcre-builtin` builds with GHC 9.0.1 if the upper bounds on `base` and `bytestring` are relaxed, see PR #17.

Blocking https://github.com/fugue/goldplate/issues/6.

**Comment by audreyt** [comment]
Thanks! Released as `regex-pcre-builtin-0.95.2.3.8.43`.
