### ISSUE TITLE
regex-pcre-builtin-0.94.4.8.8.35 no longer compiles

### ISSUE THREAD

**Issue by peti** [audreyt/regex-pcre-builtin#7]
I believe there were some updates in the regex ecosystem to accomodate the new `MonadFail` class, and it seems that those have broken `regex-pcre-builtin`:

~~~
Configuring regex-pcre-builtin-0.94.4.8.8.35...
Preprocessing library for regex-pcre-builtin-0.94.4.8.8.35..
Building library for regex-pcre-builtin-0.94.4.8.8.35..
[1 of 6] Compiling Text.Regex.PCRE.Wrap ( dist/build/Text/Regex/PCRE/Wrap.hs, dist/build/Text/Regex/PCRE/Wrap.o )

Text/Regex/PCRE/Wrap.hsc:158:33: error:
    * Could not deduce (Control.Monad.Fail.MonadFail m)
        arising from a use of `makeRegexM'
      from the context: (RegexMaker Regex CompOption ExecOption source,
                         RegexContext Regex source1 target, Monad m)
        bound by the type signature for:
                   (=~~) :: forall source source1 target (m :: * -> *).
                            (RegexMaker Regex CompOption ExecOption source,
                             RegexContext Regex source1 target, Monad m) =>
                            source1 -> source -> m target
        at Text/Regex/PCRE/Wrap.hsc:(137,1)-(138,38)
      Possible fix:
        add (Control.Monad.Fail.MonadFail m) to the context of
          the type signature for:
            (=~~) :: forall source source1 target (m :: * -> *).
                     (RegexMaker Regex CompOption ExecOption source,
                      RegexContext Regex source1 target, Monad m) =>
                     source1 -> source -> m target
    * In a stmt of a 'do' block: (q :: Regex) <- makeRegexM r
      In the expression:
        do (q :: Regex) <- makeRegexM r
           matchM q x
      In an equation for `=~~':
          (=~~) x r
            = do (q :: Regex) <- makeRegexM r
                 matchM q x
    |
158 | (=~~) x r = do (q :: Regex) <-  makeRegexM r
    |                                 ^^^^^^^^^^^^
~~~

**Comment by lierdakil** [comment]
An update to `regex-pcre` is brewing in https://github.com/haskell-hvr/regex-pcre, so it's probably a good idea to hold off on any rash actions here until that one is ready. Until then, the best option is to constrain `regex-base == 0.93.*` (best-case scenario if @audreyt or a Hackage trustee does this for regex-pcre-builtin on Hackage, but it's easy enough to constrain that downstream also).

As an experiment, I've updated the code here to the current state of haskell-hvr/regex-pcre master in [my fork](https://github.com/lierdakil/regex-pcre-builtin/tree/updates). Also, updated pcre to 8.43 (currently the latest available). That seems to work as expected.

**Comment by audreyt** [comment]
I tried the proposed `== 0.93.*` change but got this error message. I'll hold off the update for now until @lierdakil 's fork is ready for release.
```
[__1] rejecting: regex-base-0.94.0.0 (conflict: regex-pcre-builtin +/-newbase
+/-splitbase => regex-base==0.93.*)
[__1] trying: regex-base-0.93.2
[__2] next goal: base (dependency of regex-pcre-builtin +/-newbase
+/-splitbase)
[__2] rejecting: base-4.13.0.0/installed-4.1... (conflict: regex-base
+/-newbase +/-splitbase => base<4.13)
```

**Comment by lierdakil** [comment]
@audreyt, yeah, no, regex-base-0.93 is not compatible with GHC 8.8. That's the primary motivation behind regex-base-0.94 release I believe. The point of the proposed `== 0.93.*` constraint is to keep regex-pcre-builtin-0.94 buildable with GHC <= 8.6 without additional hassle downstream.

**Comment by audreyt** [comment]
OK. I've uploaded `regex-pcre-builtin-0.94.5.8.8.35` to do that but keeping this ticket open.

**Comment by sjakobi** [comment]
https://github.com/audreyt/regex-pcre-builtin/pull/9 adds support for GHC-8.8.
